# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Products.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eProducts.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x07Product\x12\x0c\n\x04shop\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"B\n\tDatePrice\x12&\n\x02ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05price\x18\x02 \x01(\x05\"G\n\x0fProductNewPrice\x12\x19\n\x07product\x18\x01 \x01(\x0b\x32\x08.Product\x12\x19\n\x05price\x18\x02 \x01(\x0b\x32\n.DatePrice\"+\n\rProductPrices\x12\x1a\n\x06prices\x18\x01 \x03(\x0b\x32\n.DatePrice\"-\n\x0bProductList\x12\x1e\n\x0cproductsList\x18\x01 \x03(\x0b\x32\x08.Product2\xdc\x01\n\x08Products\x12,\n\x10GetProductPrices\x12\x08.Product\x1a\x0e.ProductPrices\x12\x37\n\x0b\x41\x64\x64NewPrice\x12\x10.ProductNewPrice\x1a\x16.google.protobuf.Empty\x12\x31\n\rAddNewProduct\x12\x08.Product\x1a\x16.google.protobuf.Empty\x12\x36\n\x0eGetAllProducts\x12\x16.google.protobuf.Empty\x1a\x0c.ProductListB\rZ\x0b./pkg/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Products_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./pkg/proto'
  _PRODUCT._serialized_start=80
  _PRODUCT._serialized_end=130
  _DATEPRICE._serialized_start=132
  _DATEPRICE._serialized_end=198
  _PRODUCTNEWPRICE._serialized_start=200
  _PRODUCTNEWPRICE._serialized_end=271
  _PRODUCTPRICES._serialized_start=273
  _PRODUCTPRICES._serialized_end=316
  _PRODUCTLIST._serialized_start=318
  _PRODUCTLIST._serialized_end=363
  _PRODUCTS._serialized_start=366
  _PRODUCTS._serialized_end=586
# @@protoc_insertion_point(module_scope)
