# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Products_pb2 as Products__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bUsers.proto\x1a\x0eProducts.proto\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\"=\n\x0bUserProduct\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\x12\x19\n\x07product\x18\x02 \x01(\x0b\x32\x08.Product2U\n\x05Users\x12\"\n\x0bGetProducts\x12\x05.User\x1a\x0c.ProductList\x12(\n\nAddProduct\x12\x0c.UserProduct\x1a\x0c.ProductListB\rZ\x0b./pkg/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./pkg/proto'
  _USER._serialized_start=31
  _USER._serialized_end=51
  _USERPRODUCT._serialized_start=53
  _USERPRODUCT._serialized_end=114
  _USERS._serialized_start=116
  _USERS._serialized_end=201
# @@protoc_insertion_point(module_scope)
